### ISSUE TITLE
[Bug] 구글 로그인 후 "/favicon.ico" 해당 url을 호출함

### ISSUE THREAD

**Issue by jokerKwu** [newvillagetown/ticketing-backend#80]
## 에러 상세 정보
- 발생 시점 : 22/12/31
- 발견자 :  @RyanBreathings 
- 이슈 추적 방법 : 구글 로그인 후 로그 확인하면 에러 메시지 발생
- 예상 원인 : 저걸 왜 url 호출하는지 좀 찾아봐야됨.. 원인 파악 안됨, 

> 이슈 해결하기 위한 히스토리는 코멘트로 작성

<pre>
에러 메시지
/favicon.ico
code=404, message=Not Found
echo: http: panic serving [::1]:53542: runtime error: index out of range [1] with length 1
goroutine 84 [running]:
net/http.(*conn).serve.func1()
        /usr/local/opt/go/libexec/src/net/http/server.go:1850 +0xbf
panic({0x1c84da0, 0xc0006e89d8})
        /usr/local/opt/go/libexec/src/runtime/panic.go:890 +0x262
main/middleware.ErrorParsing({0xc000733640?, 0xc000014018?})
        /Users/ryan/GolandProjects/ticketing-backend/src/middleware/logging.go:62 +0x1ff
main/middleware.RestLogger.func1({0x1f4e748, 0xc0006e1900})
        /Users/ryan/GolandProjects/ticketing-backend/src/middleware/logging.go:34 +0x2a9
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x1f4e748, 0xc0006e1900})
        /Users/ryan/go/pkg/mod/github.com/labstack/echo/v4@v4.9.1/middleware/cors.go:190 +0x47e
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000fc8fc0, {0x1f434c0?, 0xc0006e4d20}, 0xc00108e900)
        /Users/ryan/go/pkg/mod/github.com/labstack/echo/v4@v4.9.1/echo.go:646 +0x3d1
net/http.serverHandler.ServeHTTP({0xc0010f2bd0?}, {0x1f434c0, 0xc0006e4d20}, 0xc00108e900)
        /usr/local/opt/go/libexec/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000fdafa0, {0x1f43f20, 0xc0010f2ae0})
        /usr/local/opt/go/libexec/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /usr/local/opt/go/libexec/src/net/http/server.go:3102 +0x4db

</pre>

### 코멘트 템플릿 
<pre> 
- 작업 시점 / 작업자 : 
- 파악된 원인 :
- 해결 방법 : 
- 해결 완료 여부 (미해결/해결완료): 
</pre>

**Comment by jokerKwu** [comment]
- 작업 시점 / 작업자 : 23/1/1, @RyanBreathings 
- 파악된 원인 : 인터넷 웹 브라우저의 주소창에 표시되는 웹사이트를 대표하는 아이콘 이미지를 호출할려고 하는데 호출을 못해서 발생하는 에러
- 해결 방법 : 서버쪽에서는 favicon 이미지 관련해서 다루지 않기 때문에 신경 안써도되지만, 이걸로 인해서 404에러가 발생시 패닉이 발생하는 문제가 발생해서 404에러 발생에 대한 에러 메시지 로깅에 구현 완료
- 해결 완료 여부 (미해결/해결완료):  해결완료
